twitter project/force-app/main/default/objects/TwitterUserAuthSettings__c/TwitterUserAuthSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TwitterUserAuthSettings</label>
</CustomObject>

twitter project/force-app/main/default/objects/TwitterUserAuthSettings__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Twitter Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

twitter project/force-app/main/default/classes/controllers/TwitterAuthController.cls
public with sharing class TwitterAuthController {
    @AuraEnabled(cacheable=false)
    public static void getAccessToken() {
        String authcode = ApexPages.currentPage().getParameters().get('code');

        if (String.isNotBlank(authcode)) {
            TwitterAuthService.newInstance().getAccessToken(authcode);
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getTwitterUserSettings() {
        try {
            TwitterUserAuthSettings__c twitterUserSetting = TwitterUserAuthSettings__c.getInstance();
            return twitterUserSetting.Username__c + '~' + twitterUserSetting.Expiration_Date__c.format('yyyy-MM-dd HH:mm:ss');
        } catch (NullPointerException e) {
            ApexLogUtils.createLog(e.getMessage(), e.getStackTraceString(), 'Could not get your twitter authentication settings. Please authenticate to twitter on Auth Twitter tab', TwitterAuthController.class.getName());
            return '';
        }
    }
}