twitter project/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>log - {0000}</displayFormat>
        <label>Log  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

twitter project/force-app/main/default/objects/Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

twitter project/force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

twitter project/force-app/main/default/objects/Log__c/fields/User_Friendly_Message__c.field-meta.xml
<CustomField>
    <fullName>User_Friendly_Message__c</fullName>
    <label>User Friendly Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

twitter project/force-app/main/default/classes/ApexLogUtils.cls
public without sharing class ApexLogUtils {
    @future
    public static void createLog(String message, String stackTrace, String userMessage, String className) {
        Log__c newLog = new Log__c();
        newLog.Message__c = message;
        newLog.StackTrace__c = stackTrace;
        newLog.User_Friendly_Message__c = userMessage;
        newLog.Class_Name__c = className;

        insert newLog;
    }

    public static void createLogs(Database.Error[] errors, String userMessage, String className) {
        List<Log__c> logList = new List<Log__c>();
        for (Database.Error error : errors) {
            Log__c newLog = new Log__c();
            newLog.Message__c = error.getMessage();
            newLog.StackTrace__c = error.getStatusCode() + ': ' + error.getFields();
            newLog.User_Friendly_Message__c = userMessage;
            newLog.Class_Name__c = className;
            logList.add(newLog);
        }

        insert logList;
    }
}