twitter project/force-app/main/default/objects/Tweet__c/Tweet__c.object-meta.xml
<CustomObject>
    <label>Tweet</label>
    <nameField>
        <label>Tweet ID</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

twitter project/force-app/main/default/objects/Tweet__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tweet</relationshipLabel>
    <relationshipName>Tweet</relationshipName>
    <type>Lookup</type>
</CustomField>

twitter project/force-app/main/default/classes/selectors/TweetSelector.cls
public with sharing class TweetSelector implements ITweetSelector {

    public static ITweetSelector newInstance() {
        return new TweetSelector();
    }

    public List<Tweet__c> getTweetsByContactID(Id contactId) {
        return [SELECT Name, Tweet_Text__c, Tweet_Date__c FROM Tweet__c WHERE Contact__c =: contactId ORDER BY Tweet_Date__c DESC LIMIT 50000];
    }

    public Tweet__c getTweetById(String tweetId) {
        try {
            return [SELECT Name FROM Tweet__c WHERE Name =: tweetId];
        } catch (QueryException e) {
            ApexLogUtils.createLog(e.getMessage(), e.getStackTraceString(), 'Something happend with retriving Tweets. Please ask administrator for help', TweetSelector.class.getName());
        }
        
        return null;
    }
}